In [ ]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [ ]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df_video_with_plane = pd.read_csv("/content/drive/MyDrive/RC - Brain Inspired Deep Learning /VIDEO_2/audio_with_train.csv")
df_video_without_plane = pd.read_csv("/content/drive/MyDrive/RC - Brain Inspired Deep Learning /VIDEO_2/audio_without_train.csv")

In [ ]:
df_video_with_plane.head()

,Unnamed: 0,0,1,2,3,4,5,6,7,8,9,10,11
0,0,0.000683,0.000093,0.000043,0.000026,0.000016,0.000018,0.000035,0.000025,0.000013,0.000011,0.000008,0.000003
1,1,0.001026,0.000309,0.000048,0.000024,0.000011,0.000014,0.000025,0.000026,0.000013,0.000010,0.000007,0.000002
2,2,0.000750,0.000197,0.000059,0.000024,0.000013,0.000015,0.000026,0.000027,0.000016,0.000012,0.000008,0.000002
3,3,0.000685,0.000097,0.000045,0.000023,0.000012,0.000014,0.000023,0.000026,0.000014,0.000013,0.000007,0.000001
4,4,0.000980,0.000423,0.000071,0.000024,0.000014,0.000017,0.000032,0.000028,0.000014,0.000012,0.000007,0.000004

In [ ]:
df1 = df_video_with_plane.drop(['Unnamed: 0'], axis=1)
df2 = df_video_without_plane.drop(['Unnamed: 0'], axis=1)

In [ ]:
df1.head()

,0,1,2,3,4,5,6,7,8,9,10,11
0,0.000683,0.000093,0.000043,0.000026,0.000016,0.000018,0.000035,0.000025,0.000013,0.000011,0.000008,0.000003
1,0.001026,0.000309,0.000048,0.000024,0.000011,0.000014,0.000025,0.000026,0.000013,0.000010,0.000007,0.000002
2,0.000750,0.000197,0.000059,0.000024,0.000013,0.000015,0.000026,0.000027,0.000016,0.000012,0.000008,0.000002
3,0.000685,0.000097,0.000045,0.000023,0.000012,0.000014,0.000023,0.000026,0.000014,0.000013,0.000007,0.000001
4,0.000980,0.000423,0.000071,0.000024,0.000014,0.000017,0.000032,0.000028,0.000014,0.000012,0.000007,0.000004

In [ ]:
df1.shape

(150, 12)

In [ ]:
mini = 100000
maxi = 0
for column in df1.columns:
  mini = min(mini,df1[column].min())
  maxi = max(maxi,df1[column].max())

for column in df2.columns:
  mini = min(mini,df2[column].min())
  maxi = max(maxi,df2[column].max())

for column in df1.columns:
  df1[column] = (df1[column] - mini) / (maxi-mini)

for column in df2.columns:
  df2[column] = (df2[column] - mini) / (maxi-mini)

In [ ]:
print(maxi,mini)

0.0042727606216193 3.996346466117945e-07

In [ ]:
df1.head()

,0,1,2,3,4,5,6,7,8,9,10,11
0,0.159858,0.021621,0.010034,0.005950,0.003540,0.004012,0.008038,0.005808,0.002876,0.002483,0.001710,0.000616
1,0.239999,0.072265,0.011132,0.005477,0.002524,0.003272,0.005653,0.006000,0.003039,0.002218,0.001606,0.000276
2,0.175487,0.045905,0.013682,0.005542,0.002890,0.003477,0.005884,0.006221,0.003638,0.002612,0.001745,0.000328
3,0.160334,0.022596,0.010452,0.005200,0.002766,0.003283,0.005240,0.006067,0.003278,0.003062,0.001654,0.000251
4,0.229221,0.098862,0.016427,0.005581,0.003236,0.003915,0.007310,0.006416,0.003206,0.002786,0.001542,0.000805

In [ ]:
df2.head()

,0,1,2,3,4,5,6,7,8,9,10,11
0,0.173275,0.020806,0.020704,0.007883,0.005390,0.003613,0.003656,0.005369,0.003363,0.003003,0.002647,0.001370
1,0.169209,0.019545,0.017701,0.007026,0.005178,0.004195,0.004474,0.006334,0.003170,0.002621,0.002613,0.000909
2,0.147484,0.019126,0.014069,0.004435,0.002298,0.002026,0.003385,0.005532,0.003556,0.003198,0.001990,0.000902
3,0.138583,0.021219,0.016043,0.005164,0.002824,0.002422,0.003666,0.006188,0.003573,0.002566,0.001744,0.000470
4,0.170403,0.019252,0.017496,0.004051,0.002075,0.002024,0.003050,0.005582,0.001933,0.002307,0.001315,0.000115

In [ ]:
# df_min_max_scaled = df.copy()

# # apply normalization techniques
# for column in df_min_max_scaled.columns:
#     df_min_max_scaled[column] = (df_min_max_scaled[column] - df_min_max_scaled[column].min()) / (df_min_max_scaled[column].max() - df_min_max_scaled[column].min())

# # view normalized data
# print(df_min_max_scaled)

In [ ]:
# df_min_max_scaled.head()

In [ ]:
df1.to_csv("/content/drive/MyDrive/RC - Brain Inspired Deep Learning /VIDEO_2/audio_with_train_normalized.csv")
df2.to_csv("/content/drive/MyDrive/RC - Brain Inspired Deep Learning /VIDEO_2/audio_without_train_normalized.csv")